### ISSUE TITLE
install不了

### ISSUE THREAD

**Issue by iamparadox** [zen0822/vue2do#4]
npm ERR! path /Users/apple/regulate/node_modules/latest/node_modules/npm/node_modules/ansistyles
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/apple/regulate/node_modules/latest/node_modules/npm/node_modules/ansistyles' -> '/Users/apple/regulate/node_modules/latest/node_modules/npm/node_modules/.ansistyles.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by iamparadox** [comment]
更新过ansistyles，还是更新不了

**Comment by zen0822** [comment]
建议 用 cnpm install ，npm 服务经常丢包
