### ISSUE TITLE
scroll组件

### ISSUE THREAD

**Issue by BH-NOTHING** [zen0822/vue2do#5]
楼主大神，已star，scroll怎么抽出来单独使用，有说明文档吗

**Comment by zen0822** [comment]
大神不敢 叫我大牛吧 ;D ,这个是基于 vue 的欸，你要移植到其他框架是吗

**Comment by zen0822** [comment]
文档在网站里面啊 https://zen0822.github.io/#/component/scroller

**Comment by BH-NOTHING** [comment]
是啊，要在vue中写成类似小程序scrollView的组件，用better-scroll实现了

**Comment by zen0822** [comment]
;D
